
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Feb 08 20:38:07 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int VLINE = 14;
  public static final int CONST = 24;
  public static final int GE = 38;
  public static final int NUMCONST = 42;
  public static final int QUE = 27;
  public static final int CAP = 33;
  public static final int HASH = 16;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int MINUS = 17;
  public static final int RPAREN = 7;
  public static final int LT = 37;
  public static final int COMMA = 8;
  public static final int INC = 20;
  public static final int DIV = 19;
  public static final int PLUS = 11;
  public static final int DOT = 22;
  public static final int LE = 39;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int EQUAL = 12;
  public static final int NEW = 26;
  public static final int error = 1;
  public static final int MUL = 18;
  public static final int DOL = 32;
  public static final int MOD = 23;
  public static final int IDENT = 43;
  public static final int VOID = 13;
  public static final int EQ = 40;
  public static final int COL = 28;
  public static final int LBRACE = 3;
  public static final int LSQUARE = 34;
  public static final int READ = 25;
  public static final int GOTO = 31;
  public static final int CHARCONST = 44;
  public static final int RSQUARE = 35;
  public static final int REPL = 15;
  public static final int FINAL = 30;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 45;
  public static final int NE = 41;
  public static final int PROG = 2;
  public static final int DEC = 21;
  public static final int AT = 29;
  public static final int GT = 36;
  public static final int PRINT = 9;
}

